//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoalInternationalEntities : DbContext
    {
        public GoalInternationalEntities()
            : base("name=GoalInternationalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<PatientInfo> PatientInfoes { get; set; }
        public virtual DbSet<PatientVisit> PatientVisits { get; set; }
        public virtual DbSet<PatientVisitDetailsV1P2> PatientVisitDetailsV1P2 { get; set; }
        public virtual DbSet<PatientVisitDetailsV1P3> PatientVisitDetailsV1P3 { get; set; }
        public virtual DbSet<PayeeInfo> PayeeInfoes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RegistrationCode> RegistrationCodes { get; set; }
        public virtual DbSet<RegistrationStatu> RegistrationStatus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatinTherapyDosageLookup> StatinTherapyDosageLookups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<PatientVisitDetailsV2P2> PatientVisitDetailsV2P2 { get; set; }
        public virtual DbSet<PatientVisitDetailsV3P2> PatientVisitDetailsV3P2 { get; set; }
        public virtual DbSet<PatientVisitDetailsV4P2> PatientVisitDetailsV4P2 { get; set; }
        public virtual DbSet<PatientVisitDetailsV2P1> PatientVisitDetailsV2P1 { get; set; }
        public virtual DbSet<PatientVisitDetailsV3P1> PatientVisitDetailsV3P1 { get; set; }
        public virtual DbSet<PatientVisitDetailsV4P1> PatientVisitDetailsV4P1 { get; set; }
        public virtual DbSet<PatientVisitDetailsV1P4> PatientVisitDetailsV1P4 { get; set; }
        public virtual DbSet<PatientVisitDetailsV2P3> PatientVisitDetailsV2P3 { get; set; }
        public virtual DbSet<PatientVisitDetailsV3P3> PatientVisitDetailsV3P3 { get; set; }
        public virtual DbSet<PatientVisitDetailsV4P3> PatientVisitDetailsV4P3 { get; set; }
        public virtual DbSet<PatientVisitDetailsV1P1> PatientVisitDetailsV1P1 { get; set; }
        public virtual DbSet<InviteesMaster> InviteesMasters { get; set; }
    }
}
