//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InviteesMaster
    {
        public int id { get; set; }
        public string AssignedPassword { get; set; }
        public Nullable<int> CHRCPhysicianID { get; set; }
        public Nullable<int> ParentUserID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserType { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Specialty { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PayableTo { get; set; }
        public string Institution { get; set; }
        public string Address { get; set; }
        public string Suite { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string CellNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public string Interest { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<int> RegistrationStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> InvitedCHRC { get; set; }
        public Nullable<System.DateTime> InvitationSentDate { get; set; }
        public string InvitationTier { get; set; }
        public Nullable<bool> ConsentCHRCShareName { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
