//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitDetailsV1P2
    {
        public int id { get; set; }
        public int PatientID { get; set; }
        public int UserID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Ethnicity { get; set; }
        public string SmokingHistory { get; set; }
        public string MedicationInsuranceCoverage { get; set; }
        public string InsuranceTypeIfPrivate { get; set; }
        public string InsuranceTypeIfOther { get; set; }
        public string CoMorbidities1 { get; set; }
        public string CoMorbidities2 { get; set; }
        public string CoMorbidities3 { get; set; }
        public string CoMorbidities4 { get; set; }
        public string CoMorbidities5 { get; set; }
        public string CoMorbidities6 { get; set; }
        public string CoMorbidities7 { get; set; }
        public string CoMorbidities8 { get; set; }
        public string CoMorbidities9 { get; set; }
        public string CoMorbidities10 { get; set; }
        public string CoMorbidities11 { get; set; }
        public string CoMorbidities12 { get; set; }
        public string CoMorbidities13 { get; set; }
        public string CoMorbidities14 { get; set; }
        public Nullable<bool> CAD1 { get; set; }
        public Nullable<bool> CAD2 { get; set; }
        public Nullable<bool> CAD3 { get; set; }
        public Nullable<bool> CAD4 { get; set; }
        public Nullable<bool> CeVD1 { get; set; }
        public Nullable<bool> CeVD2 { get; set; }
        public Nullable<bool> CeVD3 { get; set; }
        public string T2DM { get; set; }
        public Nullable<bool> MicrovascularDisease1 { get; set; }
        public Nullable<bool> MicrovascularDisease2 { get; set; }
        public Nullable<bool> MicrovascularDisease3 { get; set; }
        public Nullable<bool> MicrovascularDisease4 { get; set; }
        public Nullable<bool> FH1 { get; set; }
        public Nullable<bool> FH2 { get; set; }
        public Nullable<bool> FH3 { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
