//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitDetailsV1P1
    {
        public int id { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string Phone { get; set; }
        public string AdditionalPhone { get; set; }
        public Nullable<bool> Inclusion_1 { get; set; }
        public Nullable<bool> Inclusion_2 { get; set; }
        public Nullable<bool> Inclusion_3 { get; set; }
        public Nullable<bool> Inclusion_4 { get; set; }
        public Nullable<bool> Inclusion_5 { get; set; }
        public Nullable<bool> Exclusion { get; set; }
        public string PatientConsentDate { get; set; }
        public string VisitDate { get; set; }
        public Nullable<bool> SignOff { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LDLCYesNo { get; set; }
    }
}
