//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitDetailsV2P2
    {
        public int id { get; set; }
        public int PatientID { get; set; }
        public int UserID { get; set; }
        public string CurrentLDLTherapy1 { get; set; }
        public string CurrentLDLTherapy2 { get; set; }
        public string CurrentLDLTherapy3 { get; set; }
        public string CurrentLDLTherapy4 { get; set; }
        public string CurrentLDLTherapy5 { get; set; }
        public string CurrentLDLTherapy6 { get; set; }
        public Nullable<int> Systolic { get; set; }
        public Nullable<int> Diastolic { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string HeightUnit { get; set; }
        public Nullable<decimal> WaistCircumference { get; set; }
        public string WaistCircumferenceUnit { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
