//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitDetailsV2P1
    {
        public int id { get; set; }
        public int PatientID { get; set; }
        public int UserID { get; set; }
        public string IsPatientLFU { get; set; }
        public string LFUReason { get; set; }
        public string VisitDate { get; set; }
        public string Experience1 { get; set; }
        public string Experience2 { get; set; }
        public string Experience3 { get; set; }
        public string Experience4 { get; set; }
        public string Experience5 { get; set; }
        public Nullable<bool> SignOff { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LDLCYesNo { get; set; }
    }
}
