//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<int> PatientType { get; set; }
        public string Initials { get; set; }
    }
}
