//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost To FollowUp.
        /// </summary>
        public static string LostToFollowUp {
            get {
                return ResourceManager.GetString("LostToFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed.
        /// </summary>
        public static string NotComplete {
            get {
                return ResourceManager.GetString("NotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Consent Date.
        /// </summary>
        public static string PatientConsentDate {
            get {
                return ResourceManager.GetString("PatientConsentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientID {
            get {
                return ResourceManager.GetString("PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Initials.
        /// </summary>
        public static string PatientInitials {
            get {
                return ResourceManager.GetString("PatientInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI Email.
        /// </summary>
        public static string PIEmail {
            get {
                return ResourceManager.GetString("PIEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI First Name.
        /// </summary>
        public static string PIFirstName {
            get {
                return ResourceManager.GetString("PIFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI Last Name.
        /// </summary>
        public static string PILastName {
            get {
                return ResourceManager.GetString("PILastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI Phone.
        /// </summary>
        public static string PIPhone {
            get {
                return ResourceManager.GetString("PIPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit1 Completion Date.
        /// </summary>
        public static string Visit1CompletionDate {
            get {
                return ResourceManager.GetString("Visit1CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit1 Status.
        /// </summary>
        public static string Visit1Status {
            get {
                return ResourceManager.GetString("Visit1Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit2 Completion Date.
        /// </summary>
        public static string Visit2CompletionDate {
            get {
                return ResourceManager.GetString("Visit2CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit2 Lost To Followup Reason.
        /// </summary>
        public static string Visit2LostToFollowupReason {
            get {
                return ResourceManager.GetString("Visit2LostToFollowupReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit2 Status.
        /// </summary>
        public static string Visit2Status {
            get {
                return ResourceManager.GetString("Visit2Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit3 Completion Date.
        /// </summary>
        public static string Visit3CompletionDate {
            get {
                return ResourceManager.GetString("Visit3CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit3 Lost To Followup Reason.
        /// </summary>
        public static string Visit3LostToFollowupReason {
            get {
                return ResourceManager.GetString("Visit3LostToFollowupReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit3 Status.
        /// </summary>
        public static string Visit3Status {
            get {
                return ResourceManager.GetString("Visit3Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit4 Completion Date.
        /// </summary>
        public static string Visit4CompletionDate {
            get {
                return ResourceManager.GetString("Visit4CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit4 Lost To Followup Reason.
        /// </summary>
        public static string Visit4LostToFollowupReason {
            get {
                return ResourceManager.GetString("Visit4LostToFollowupReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit4 Status.
        /// </summary>
        public static string Visit4Status {
            get {
                return ResourceManager.GetString("Visit4Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
    }
}
