//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width = &apos;500&apos; border = &apos;0&apos; cellspacing = &apos;0&apos; cellpadding = &apos;10&apos;&gt;
        ///                        &lt;tr&gt;
        ///                
        ///                            &lt;td align = &apos;center&apos;&gt;&lt;strong style = &apos;font-size: 30px; font-family: Arial, Helvetica, sans-serif;&apos;&gt; REGISTRATION COMPLETE &lt;/strong&gt;&lt;/td&gt;
        ///                         
        ///                                 &lt;/tr&gt;
        ///                         
        ///                              
        ///                         
        ///                                 &lt;tr&gt;
        ///                         
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActivationEmail {
            get {
                return ResourceManager.GetString("ActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 259 Yorkland Road, Suite 200,.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have one of the following as an inclusion criteria, Coronary Artery Disease, Cerebrovascular Disease, Abdominal Aortic Aneurism, Peripheral Arterial Disease or Familial Hypercholesterolemia.
        /// </summary>
        public static string AtLeastOneCVD {
            get {
                return ResourceManager.GetString("AtLeastOneCVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atorvastatin.
        /// </summary>
        public static string Atorvastatin {
            get {
                return ResourceManager.GetString("Atorvastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North York, Ontario,.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada, M2J 5B2.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be earlier than 2019-04-01.
        /// </summary>
        public static string DateNotBefore {
            get {
                return ResourceManager.GetString("DateNotBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Diastolic Range is 30 to 150.
        /// </summary>
        public static string DiastolicOutOfRange {
            get {
                return ResourceManager.GetString("DiastolicOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Email is Invalid.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluvastatin.
        /// </summary>
        public static string Fluvastatin {
            get {
                return ResourceManager.GetString("Fluvastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT PASSWORD.
        /// </summary>
        public static string FORGOT_PWD_HEADER {
            get {
                return ResourceManager.GetString("FORGOT_PWD_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width = &apos;500&apos; border = &apos;0&apos; cellspacing = &apos;0&apos; cellpadding = &apos;10&apos;&gt;
        ///                        &lt;tr&gt;                
        ///                            &lt;td align = &apos;center&apos;&gt;&lt;strong style = &apos;font-size: 30px; font-family: Arial, Helvetica, sans-serif;&apos;&gt; FORGOT PASSWORD &lt;/strong&gt;&lt;/td&gt;                         
        ///                                 &lt;/tr&gt;                       
        ///                         
        ///                                 &lt;tr&gt;                         
        ///                                     &lt;td align = &apos;left [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FORGOTPASSWORD_TEXT {
            get {
                return ResourceManager.GetString("FORGOTPASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Heart Rate is 30 to 200.
        /// </summary>
        public static string HeartRateOutOfRange {
            get {
                return ResourceManager.GetString("HeartRateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Centre.
        /// </summary>
        public static string HelpCentre {
            get {
                return ResourceManager.GetString("HelpCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS.
        /// </summary>
        public static string INSTRUCTIONS {
            get {
                return ResourceManager.GetString("INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please do not start this visit (virtual or in person) unless you have this subject’s LDL-C drawn within the last 3 months, or since the last visit.&lt;/p&gt;&lt;p&gt;You can not enter the LDL-C value from the bloodwork done at this subject’s previous visit and you can not enter the LDL-C if taken after this visit’s date.&lt;/p&gt;&lt;p&gt;If you do not have this subject’s LDL-C today, please wait until you do and complete this visit then with the then current date.  
        ///After enrollment (visit 1), each follow up visit should be &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Date cannot be later than Visit Date.
        /// </summary>
        public static string LabDateErrMsg {
            get {
                return ResourceManager.GetString("LabDateErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not start this visit (virtual or in person) unless you have this subject’s LDL-C drawn within the last 3 months, or since the last visit..
        /// </summary>
        public static string LDLCYesNoErrMsg {
            get {
                return ResourceManager.GetString("LDLCYesNoErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovastatin.
        /// </summary>
        public static string Lovastatin {
            get {
                return ResourceManager.GetString("Lovastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password has been sent to you..
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Statin.
        /// </summary>
        public static string NoStatin {
            get {
                return ResourceManager.GetString("NoStatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a number.
        /// </summary>
        public static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitavastatin.
        /// </summary>
        public static string Pitavastatin {
            get {
                return ResourceManager.GetString("Pitavastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of them.
        /// </summary>
        public static string PleaseSelectOne {
            get {
                return ResourceManager.GetString("PleaseSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravastatin.
        /// </summary>
        public static string Pravastatin {
            get {
                return ResourceManager.GetString("Pravastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration - Language Selection.
        /// </summary>
        public static string Registration_Language_Selection {
            get {
                return ResourceManager.GetString("Registration_Language_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required Field.
        /// </summary>
        public static string RequiredFieldWithAsterisk {
            get {
                return ResourceManager.GetString("RequiredFieldWithAsterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosuvastatin.
        /// </summary>
        public static string Rosuvastatin {
            get {
                return ResourceManager.GetString("Rosuvastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save in database, please contact info@goalinternational.com support.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is saved in database successfully..
        /// </summary>
        public static string SaveSucess {
            get {
                return ResourceManager.GetString("SaveSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ALL that Apply (at least ONE must be checked).
        /// </summary>
        public static string SelectAllApply {
            get {
                return ResourceManager.GetString("SelectAllApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one from the drop down menu.
        /// </summary>
        public static string SelectOneDropDown {
            get {
                return ResourceManager.GetString("SelectOneDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string SelectYesNo {
            get {
                return ResourceManager.GetString("SelectYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simvastatin.
        /// </summary>
        public static string Simvastatin {
            get {
                return ResourceManager.GetString("Simvastatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEERING COMMITTEE.
        /// </summary>
        public static string SteeringCommittee {
            get {
                return ResourceManager.GetString("SteeringCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol&gt;
        ///    &lt;li&gt;Anatoly Langer, MD (Chair) langera@chrc.net&lt;/li&gt;
        ///    &lt;li&gt;Khalid Al Faraidy, MD (King Fahad Military Medical Complex, Saudi Arabia) kalfaraidy@yahoo.com&lt;/li&gt;
        ///    &lt;li&gt;Mousa Akbar, MD (Sabah Hospital, Kuwait) mousaakbar@hotmail.com&lt;/li&gt;
        ///    &lt;li&gt;Wael Almahmeed, MD (Cleveland Clinic, Abu Dhabi) wmahmeed@gmail.com&lt;/li&gt;
        ///    &lt;li&gt;Marco Antonio Alcocer-Gamba, MD (Mexican Society of Cardiology, Mexico) marco.alcocerg@gmail.com&lt;/li&gt;
        ///    &lt;li&gt;Otavio Berwanger, MD (Albert Einstein Hospital) otavioberwan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SteeringCommitteeDetails {
            get {
                return ResourceManager.GetString("SteeringCommitteeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Systolic Range is 60 to 250.
        /// </summary>
        public static string SystolicOutOfRange {
            get {
                return ResourceManager.GetString("SystolicOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(0.05-50 g/L or 5-5000 mg/dL).
        /// </summary>
        public static string ValidApoBRange {
            get {
                return ResourceManager.GetString("ValidApoBRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(0.01 g/L- 10 g/L).
        /// </summary>
        public static string ValidateApoB {
            get {
                return ResourceManager.GetString("ValidateApoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be equal or earlier than current date.
        /// </summary>
        public static string ValidateDate {
            get {
                return ResourceManager.GetString("ValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not a valid date.
        /// </summary>
        public static string ValidateDateFormat {
            get {
                return ResourceManager.GetString("ValidateDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(0.5-25 mmol/L or 30-2215 mg/dL).
        /// </summary>
        public static string ValidateTriglycerides {
            get {
                return ResourceManager.GetString("ValidateTriglycerides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(0.5-25 mmol/L or 20-967 mg/dL).
        /// </summary>
        public static string ValidHDLCRange {
            get {
                return ResourceManager.GetString("ValidHDLCRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Height Range is (100-230 cm or 39-90 inch).
        /// </summary>
        public static string ValidHeightRange {
            get {
                return ResourceManager.GetString("ValidHeightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either LDL-C, Non HDL-C, or Apo-B must be filled in.
        /// </summary>
        public static string ValidLabValues {
            get {
                return ResourceManager.GetString("ValidLabValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(1.4-20 mmol/L or 55-800 mg/dL).
        /// </summary>
        public static string ValidLDLCRange {
            get {
                return ResourceManager.GetString("ValidLDLCRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(2.5-25 mmol/L or 100-967 mg/dL).
        /// </summary>
        public static string ValidNHDLCRange {
            get {
                return ResourceManager.GetString("ValidNHDLCRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(2-25 mmol/L or 80-967 mg/dL).
        /// </summary>
        public static string ValidTotalCholesterolRange {
            get {
                return ResourceManager.GetString("ValidTotalCholesterolRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(0.1-20 mmol/L or 1-800 mg/dL).
        /// </summary>
        public static string ValidV2V3V4LDLCRange {
            get {
                return ResourceManager.GetString("ValidV2V3V4LDLCRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(1-25 mmol/L or 30-967 mg/dL).
        /// </summary>
        public static string ValidV2V3V4NHDLCRange {
            get {
                return ResourceManager.GetString("ValidV2V3V4NHDLCRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Valid range(1-25 mmol/L or 35-967 mg/dL).
        /// </summary>
        public static string ValidV2V3V4TotalCholesterolRange {
            get {
                return ResourceManager.GetString("ValidV2V3V4TotalCholesterolRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Waist Range is (18-80 inch or 45-200 cm).
        /// </summary>
        public static string ValidWaistRange {
            get {
                return ResourceManager.GetString("ValidWaistRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Weight Range is (30-300 kg or 66-660 lb).
        /// </summary>
        public static string ValidWeightRange {
            get {
                return ResourceManager.GetString("ValidWeightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be earlier than Patient Consent Date.
        /// </summary>
        public static string VisitDateNotBeforeConsentDate {
            get {
                return ResourceManager.GetString("VisitDateNotBeforeConsentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        public static string year_1 {
            get {
                return ResourceManager.GetString("year_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 year.
        /// </summary>
        public static string year_less_1 {
            get {
                return ResourceManager.GetString("year_less_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 years.
        /// </summary>
        public static string years_10 {
            get {
                return ResourceManager.GetString("years_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 years.
        /// </summary>
        public static string years_11 {
            get {
                return ResourceManager.GetString("years_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 years.
        /// </summary>
        public static string years_12 {
            get {
                return ResourceManager.GetString("years_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 years.
        /// </summary>
        public static string years_13 {
            get {
                return ResourceManager.GetString("years_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 years.
        /// </summary>
        public static string years_14 {
            get {
                return ResourceManager.GetString("years_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 years.
        /// </summary>
        public static string years_15 {
            get {
                return ResourceManager.GetString("years_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 years.
        /// </summary>
        public static string years_16 {
            get {
                return ResourceManager.GetString("years_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 years.
        /// </summary>
        public static string years_17 {
            get {
                return ResourceManager.GetString("years_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 years.
        /// </summary>
        public static string years_18 {
            get {
                return ResourceManager.GetString("years_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 years.
        /// </summary>
        public static string years_19 {
            get {
                return ResourceManager.GetString("years_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 years.
        /// </summary>
        public static string years_2 {
            get {
                return ResourceManager.GetString("years_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 years.
        /// </summary>
        public static string years_20 {
            get {
                return ResourceManager.GetString("years_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 years.
        /// </summary>
        public static string years_21 {
            get {
                return ResourceManager.GetString("years_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 years.
        /// </summary>
        public static string years_22 {
            get {
                return ResourceManager.GetString("years_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 years.
        /// </summary>
        public static string years_23 {
            get {
                return ResourceManager.GetString("years_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 years.
        /// </summary>
        public static string years_24 {
            get {
                return ResourceManager.GetString("years_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 years.
        /// </summary>
        public static string years_25 {
            get {
                return ResourceManager.GetString("years_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 years.
        /// </summary>
        public static string years_3 {
            get {
                return ResourceManager.GetString("years_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 years.
        /// </summary>
        public static string years_4 {
            get {
                return ResourceManager.GetString("years_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 years.
        /// </summary>
        public static string years_5 {
            get {
                return ResourceManager.GetString("years_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 years.
        /// </summary>
        public static string years_6 {
            get {
                return ResourceManager.GetString("years_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 years.
        /// </summary>
        public static string years_7 {
            get {
                return ResourceManager.GetString("years_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 years.
        /// </summary>
        public static string years_8 {
            get {
                return ResourceManager.GetString("years_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 years.
        /// </summary>
        public static string years_9 {
            get {
                return ResourceManager.GetString("years_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 25  years.
        /// </summary>
        public static string years_greater_25 {
            get {
                return ResourceManager.GetString("years_greater_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
