//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GIntV1P3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GIntV1P3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.GIntV1P3", typeof(GIntV1P3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCRF Portal - Add New Patient.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium Channel Blocker.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diuretic.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warfarin.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct  Oral Anticoagulation Agent.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valsartan/Succubitril.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spironolactone/Eplerenon.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTIHYPERGLYCEMIC MEDICATION.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a-Glucosidase Inhibitor.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPP-4 Inhibitor.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDICATION AND PHYSICAL ASSESSMENT.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLP-1 Receptor Agonist.
        /// </summary>
        public static string G20 {
            get {
                return ResourceManager.GetString("G20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulin.
        /// </summary>
        public static string G21 {
            get {
                return ResourceManager.GetString("G21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meglitinide.
        /// </summary>
        public static string G22 {
            get {
                return ResourceManager.GetString("G22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metformin.
        /// </summary>
        public static string G23 {
            get {
                return ResourceManager.GetString("G23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metformin/DPP-4 Fixed Dose Combination.
        /// </summary>
        public static string G24 {
            get {
                return ResourceManager.GetString("G24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGLT2 Inhibitor.
        /// </summary>
        public static string G25 {
            get {
                return ResourceManager.GetString("G25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfonylurea.
        /// </summary>
        public static string G26 {
            get {
                return ResourceManager.GetString("G26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiazolidinedione.
        /// </summary>
        public static string G27 {
            get {
                return ResourceManager.GetString("G27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT LDL LOWERING THERAPY:.
        /// </summary>
        public static string G28 {
            get {
                return ResourceManager.GetString("G28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string G29 {
            get {
                return ResourceManager.GetString("G29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Number:.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statin.
        /// </summary>
        public static string G30 {
            get {
                return ResourceManager.GetString("G30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bile Acid Sequestrant.
        /// </summary>
        public static string G31 {
            get {
                return ResourceManager.GetString("G31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezetimibe.
        /// </summary>
        public static string G32 {
            get {
                return ResourceManager.GetString("G32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrate.
        /// </summary>
        public static string G33 {
            get {
                return ResourceManager.GetString("G33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niacin.
        /// </summary>
        public static string G34 {
            get {
                return ResourceManager.GetString("G34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string G35 {
            get {
                return ResourceManager.GetString("G35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that this patient is on maximal tolerated statin dose which may include no statin therapy in case of complete intolerance.
        /// </summary>
        public static string G36 {
            get {
                return ResourceManager.GetString("G36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICAL ASSESSMENT.
        /// </summary>
        public static string G37 {
            get {
                return ResourceManager.GetString("G37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic.
        /// </summary>
        public static string G38 {
            get {
                return ResourceManager.GetString("G38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic.
        /// </summary>
        public static string G39 {
            get {
                return ResourceManager.GetString("G39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT MEDICATION (OTHER THAN LIPID MODIFYING THERAPY).
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        public static string G40 {
            get {
                return ResourceManager.GetString("G40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string G41 {
            get {
                return ResourceManager.GetString("G41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string G42 {
            get {
                return ResourceManager.GetString("G42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iliac Waist Circumference.
        /// </summary>
        public static string G43 {
            get {
                return ResourceManager.GetString("G43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Iliac Waist Circumference is Not Available, check the N/A box.
        /// </summary>
        public static string G44 {
            get {
                return ResourceManager.GetString("G44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic cannot be more than Systolic.
        /// </summary>
        public static string G45 {
            get {
                return ResourceManager.GetString("G45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Antiplatelet Agent (Clopidogrel, Prasugrel, Ticagrelor).
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE-Inhibitor.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiotensin Receptor Blocker (ARB).
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta-Blocker.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
