//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GIntV1P4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GIntV1P4() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.GIntV1P4", typeof(GIntV1P4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIPID PROFILE AND MANAGEMENT.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apo-B:.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Statin Therapy:.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In light of the LDL-C and/or non-HDL-C level will you add one or more of the following lipid lowering therapies?.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bile Acid Sequestrant.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrate.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezetimibe.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the most applicable reason for.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not providing the Ezetimibe prescription.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to this patient at this visit:.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Number:.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only one.
        /// </summary>
        public static string G20 {
            get {
                return ResourceManager.GetString("G20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Refusal.
        /// </summary>
        public static string G21 {
            get {
                return ResourceManager.GetString("G21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient intolerant.
        /// </summary>
        public static string G22 {
            get {
                return ResourceManager.GetString("G22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Needed.
        /// </summary>
        public static string G23 {
            get {
                return ResourceManager.GetString("G23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-morbidities.
        /// </summary>
        public static string G24 {
            get {
                return ResourceManager.GetString("G24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string G25 {
            get {
                return ResourceManager.GetString("G25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is on PCSK9i.
        /// </summary>
        public static string G26 {
            get {
                return ResourceManager.GetString("G26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient will return for Rx/Will provide Rx at next patient visit..
        /// </summary>
        public static string G27 {
            get {
                return ResourceManager.GetString("G27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that ezetimibe is recommended to achieve lower LDL..
        /// </summary>
        public static string G28 {
            get {
                return ResourceManager.GetString("G28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the most applicable reason for not providing the.
        /// </summary>
        public static string G29 {
            get {
                return ResourceManager.GetString("G29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record values exactly as they appear in the lab report.  Include decimal places where applicable.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prescription to this patient at this visit:.
        /// </summary>
        public static string G30 {
            get {
                return ResourceManager.GetString("G30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that PCSK9i is recommended to achieve lower LDL..
        /// </summary>
        public static string G31 {
            get {
                return ResourceManager.GetString("G31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCSK9i (evolocumab).
        /// </summary>
        public static string G32 {
            get {
                return ResourceManager.GetString("G32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCSK9i (alirocumab).
        /// </summary>
        public static string G33 {
            get {
                return ResourceManager.GetString("G33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent Lab Date: (yyyy/mm/dd).
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cholesterol:.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDL-C.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDL-C.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non HDL-C.
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triglycerides:.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
