//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GIntV2P2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GIntV2P2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.GIntV2P2", typeof(GIntV2P2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCRF Portal.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iliac Waist Circumference.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Iliac Waist Circumference is Not Available, check the N/A box.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT LDL LOWERING THERAPY:.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Yes/No for each of the following.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statin.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bile Acid Sequestrant.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ezetimibe.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrate.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niacin.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDICATION AND PHYSICAL ASSESSMENT.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Number:.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICAL ASSESSMENT.
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolic.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolic.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
