//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GIntV1P2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GIntV1P2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.GIntV1P2", typeof(GIntV1P2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCRF Portal.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic / North African.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caucasian / White.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hispanic.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East / South-East Asian.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Racial.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Asian.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Smoked.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Smoker.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMOGRAPHICS AND HISTORY.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Smoker.
        /// </summary>
        public static string G20 {
            get {
                return ResourceManager.GetString("G20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string G21 {
            get {
                return ResourceManager.GetString("G21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string G22 {
            get {
                return ResourceManager.GetString("G22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Private.
        /// </summary>
        public static string G23 {
            get {
                return ResourceManager.GetString("G23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string G24 {
            get {
                return ResourceManager.GetString("G24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Pay.
        /// </summary>
        public static string G25 {
            get {
                return ResourceManager.GetString("G25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string G26 {
            get {
                return ResourceManager.GetString("G26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO-MORBIDITIES.
        /// </summary>
        public static string G27 {
            get {
                return ResourceManager.GetString("G27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronary Artery Disease.
        /// </summary>
        public static string G28 {
            get {
                return ResourceManager.GetString("G28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebrovascular Disease.
        /// </summary>
        public static string G29 {
            get {
                return ResourceManager.GetString("G29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Number.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdominal Aortic Aneurism.
        /// </summary>
        public static string G30 {
            get {
                return ResourceManager.GetString("G30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Arterial Disease.
        /// </summary>
        public static string G31 {
            get {
                return ResourceManager.GetString("G31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes Mellitus.
        /// </summary>
        public static string G32 {
            get {
                return ResourceManager.GetString("G32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treated Hypertension.
        /// </summary>
        public static string G33 {
            get {
                return ResourceManager.GetString("G33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Kidney Disease.
        /// </summary>
        public static string G34 {
            get {
                return ResourceManager.GetString("G34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microvascular Disease (retinopathy, neuropathy).
        /// </summary>
        public static string G35 {
            get {
                return ResourceManager.GetString("G35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familial Hypercholesterolemia.
        /// </summary>
        public static string G36 {
            get {
                return ResourceManager.GetString("G36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premature Family History or CV disease (1º relative – 55 yo/male, 65 yo/female).
        /// </summary>
        public static string G37 {
            get {
                return ResourceManager.GetString("G37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atrial Fibrillation.
        /// </summary>
        public static string G38 {
            get {
                return ResourceManager.GetString("G38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congestive Heart Failure.
        /// </summary>
        public static string G39 {
            get {
                return ResourceManager.GetString("G39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string G40 {
            get {
                return ResourceManager.GetString("G40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liver Disease.
        /// </summary>
        public static string G41 {
            get {
                return ResourceManager.GetString("G41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of Coronary Artery Disease (CAD).
        /// </summary>
        public static string G42 {
            get {
                return ResourceManager.GetString("G42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myocardial Infarction.
        /// </summary>
        public static string G43 {
            get {
                return ResourceManager.GetString("G43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronary artery bypass surgery.
        /// </summary>
        public static string G44 {
            get {
                return ResourceManager.GetString("G44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percutaneous coronary intervention.
        /// </summary>
        public static string G45 {
            get {
                return ResourceManager.GetString("G45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angiographic disease (&gt;50% stenosis).
        /// </summary>
        public static string G46 {
            get {
                return ResourceManager.GetString("G46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of Cerebrovascular Disease (CeVD).
        /// </summary>
        public static string G47 {
            get {
                return ResourceManager.GetString("G47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebrovascular Accident.
        /// </summary>
        public static string G48 {
            get {
                return ResourceManager.GetString("G48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient ischemic attack.
        /// </summary>
        public static string G49 {
            get {
                return ResourceManager.GetString("G49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carotid Surgery.
        /// </summary>
        public static string G50 {
            get {
                return ResourceManager.GetString("G50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T2DM Duration.
        /// </summary>
        public static string G51 {
            get {
                return ResourceManager.GetString("G51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microvascular Disease.
        /// </summary>
        public static string G52 {
            get {
                return ResourceManager.GetString("G52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microalbuminuria.
        /// </summary>
        public static string G53 {
            get {
                return ResourceManager.GetString("G53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eGFR &lt; 60 mL/min.
        /// </summary>
        public static string G54 {
            get {
                return ResourceManager.GetString("G54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuropathy.
        /// </summary>
        public static string G55 {
            get {
                return ResourceManager.GetString("G55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retinopathy.
        /// </summary>
        public static string G56 {
            get {
                return ResourceManager.GetString("G56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familial Hypercholesterolemia LDL-C &gt; 5mmol/L prior to lipid lowering therapy and one of:.
        /// </summary>
        public static string G57 {
            get {
                return ResourceManager.GetString("G57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical physical findings (stigmata) such as tendon xanthomata, xanthelasma, and corneal arcus.
        /// </summary>
        public static string G58 {
            get {
                return ResourceManager.GetString("G58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal history of premature cardiovascular disease.
        /// </summary>
        public static string G59 {
            get {
                return ResourceManager.GetString("G59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family history of premature cardiovascular disease or of marked hyperlipidemia.
        /// </summary>
        public static string G60 {
            get {
                return ResourceManager.GetString("G60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking History: &lt;em&gt;Select one from the drop down menu&lt;/em&gt;.
        /// </summary>
        public static string G61 {
            get {
                return ResourceManager.GetString("G61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Insurance Coverage:.
        /// </summary>
        public static string G62 {
            get {
                return ResourceManager.GetString("G62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Insurance Coverage:.
        /// </summary>
        public static string G63 {
            get {
                return ResourceManager.GetString("G63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age cannot be younger than 18 or older than 110.
        /// </summary>
        public static string G64 {
            get {
                return ResourceManager.GetString("G64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdominal Aortic Aneurism (AAA): History of surgery/intervention.
        /// </summary>
        public static string G65 {
            get {
                return ResourceManager.GetString("G65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Arterial Disease (PAD): History of surgery/intervention.
        /// </summary>
        public static string G66 {
            get {
                return ResourceManager.GetString("G66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical physical findings (stigmata) such as tendon xanthomata, xanthelasma, and corneal arcus. Personal history of premature cardiovascular disease. Family history of premature cardiovascular disease or of marked hyperlipidemia.
        /// </summary>
        public static string G67 {
            get {
                return ResourceManager.GetString("G67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronic Kidney Disease GFR ≤ 45 mL/min/1.73 m2 or albumin: creatinine ratio (ACR) of ≥ 30 mg/mmol (≥ 300 mg/day).
        /// </summary>
        public static string G68 {
            get {
                return ResourceManager.GetString("G68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age: (years).
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity: Select one from the drop down menu.
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aboriginal Canadian (First Nations / Métis / Inuit).
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
