//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.HomeIndex", typeof(HomeIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Centre:.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manual outlining the web-portal functionalities.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician Specific Requirements.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee Form.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and Forms.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol, country relevant guidelines, Central Ethics Approval Forms and the Informed Consent Form where required.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Functions and General Documents and Materials.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-CRF Portal.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simple and streamlined e-CRF for eligible patient enrollment and follow up.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GOAL International Program team is happy to assist you with any questions. Please do not hesitate to contact us at any time:.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On behalf of the Canadian Heart Research Centre (CHRC) and the international steering committee, welcome to your personal online portal and thank you for your participation..
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string G20 {
            get {
                return ResourceManager.GetString("G20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We look forward to collaborating with you..
        /// </summary>
        public static string G21 {
            get {
                return ResourceManager.GetString("G21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With best regards,.
        /// </summary>
        public static string G22 {
            get {
                return ResourceManager.GetString("G22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anatoly Langer MD, M.Sc., FRCP (C), FACC.
        /// </summary>
        public static string G23 {
            get {
                return ResourceManager.GetString("G23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair, Canadian Heart Research Centre.
        /// </summary>
        public static string G24 {
            get {
                return ResourceManager.GetString("G24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor of Medicine, University of Toronto.
        /// </summary>
        public static string G25 {
            get {
                return ResourceManager.GetString("G25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Investigator, GOAL International Program.
        /// </summary>
        public static string G26 {
            get {
                return ResourceManager.GetString("G26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GOAL International Program will involve over 100 physicians and 2,500 patients in five countries. GOAL International Program is supported by Amgen as investigator sponsored study (ISS)..
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL International Program will identify high risk cardiovascular patients who have not achieved recommended LDL-C level despite statin therapy (± other lipid lowering therapy) and will provide further insights into the challenges physicians face in lowering LDL-C to desirable level based on country specific guidelines or recommendations..
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The online portal has been created to provide participating physicians with program materials, convenient way to manage program documents and complete the electronic case report forms (e-CRFs). Please keep your username and password confidential..
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to download documents, you will need to enable cookies in your browser. Please follow the link for additional information:.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Cookies.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a few minutes to familiarize yourself with the program requirements and the site functionalities..
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your online portal consists of the following:.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
