//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalInternational.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoalInternational.Languages.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///  Dear {firstName} {lastName},
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///  Dr. {piLastName} at your Institution {institution} has identified you as a Study Coordinator for the GoalInternational program.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///  On behalf of the Canadian Heart Research Centre and the GOAL International program Steering Committee, we look forward to working with you and appreciate your contribution to this program.
        ///&lt;/p&gt;
        ///&lt;div style=&quot;font-weight:bold&quot;&gt;
        ///&lt;p style=&quot;text-decoration:underline; font-weight: bold&quot;&gt;
        ///  To register and access your Inst [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailContentToSC {
            get {
                return ResourceManager.GetString("EmailContentToSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///  Dear Dr. {lastName},
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///  Dr. {piLastName} at your Institution {institution} has identified you as a Sub-Investigator for the GoalInternational program.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///  On behalf of the Canadian Heart Research Centre and the GOAL International program Steering Committee, we look forward to working with you and appreciate your contribution to this program.
        ///&lt;/p&gt;
        ///&lt;div style=&quot;font-weight:bold&quot;&gt;
        ///&lt;p style=&quot;text-decoration:underline; font-weight: bold&quot;&gt;
        ///  To register and access your Institution’s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailContentToSI {
            get {
                return ResourceManager.GetString("EmailContentToSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal International  – Registration.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub-Investigator.
        /// </summary>
        public static string G1 {
            get {
                return ResourceManager.GetString("G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string G10 {
            get {
                return ResourceManager.GetString("G10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter Email.
        /// </summary>
        public static string G11 {
            get {
                return ResourceManager.GetString("G11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Re-Enter Email&quot; and &quot;Email&quot; do not match.
        /// </summary>
        public static string G12 {
            get {
                return ResourceManager.GetString("G12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully added a new Sub-Investigator.
        /// </summary>
        public static string G13 {
            get {
                return ResourceManager.GetString("G13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person with this email has been added before.
        /// </summary>
        public static string G14 {
            get {
                return ResourceManager.GetString("G14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITION SUCCESSFUL.
        /// </summary>
        public static string G15 {
            get {
                return ResourceManager.GetString("G15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDITION FAILED.
        /// </summary>
        public static string G16 {
            get {
                return ResourceManager.GetString("G16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Study Coordinator.
        /// </summary>
        public static string G17 {
            get {
                return ResourceManager.GetString("G17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a Study Coordinator and provide them access to your Goal portal, please complete the mandatory fields (*) and click the &quot;Add&quot; button.
        /// </summary>
        public static string G18 {
            get {
                return ResourceManager.GetString("G18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory fields are marked with an asterisk: *.
        /// </summary>
        public static string G19 {
            get {
                return ResourceManager.GetString("G19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string G2 {
            get {
                return ResourceManager.GetString("G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully added a new Study Coordinator.
        /// </summary>
        public static string G20 {
            get {
                return ResourceManager.GetString("G20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Sub-Investigator.
        /// </summary>
        public static string G21 {
            get {
                return ResourceManager.GetString("G21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove the Sub-Investigator and discontinue their online portal access, please click the &quot;Remove&quot; button next to the appropriate name in the list below.
        /// </summary>
        public static string G22 {
            get {
                return ResourceManager.GetString("G22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB-INVESTIGATOR LIST.
        /// </summary>
        public static string G23 {
            get {
                return ResourceManager.GetString("G23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Last Name.
        /// </summary>
        public static string G24 {
            get {
                return ResourceManager.GetString("G24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search First Name.
        /// </summary>
        public static string G25 {
            get {
                return ResourceManager.GetString("G25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        public static string G26 {
            get {
                return ResourceManager.GetString("G26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Sub Investigator?.
        /// </summary>
        public static string G27 {
            get {
                return ResourceManager.GetString("G27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Failed.
        /// </summary>
        public static string G28 {
            get {
                return ResourceManager.GetString("G28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Study Coordinator.
        /// </summary>
        public static string G29 {
            get {
                return ResourceManager.GetString("G29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a Sub-Investigator and provide them access to your Goal portal , please complete the mandatory fields (*) and click the &quot;Add&quot; button.
        /// </summary>
        public static string G3 {
            get {
                return ResourceManager.GetString("G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove the Study Coordinator and discontinue their online portal access, please click the &quot;Remove&quot; button next to the appropriate name in the list below.
        /// </summary>
        public static string G30 {
            get {
                return ResourceManager.GetString("G30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STUDY COORDINATOR LIST.
        /// </summary>
        public static string G31 {
            get {
                return ResourceManager.GetString("G31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Study Coordinator?.
        /// </summary>
        public static string G32 {
            get {
                return ResourceManager.GetString("G32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigator Meeting Presentations.
        /// </summary>
        public static string G33 {
            get {
                return ResourceManager.GetString("G33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string G34 {
            get {
                return ResourceManager.GetString("G34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction - Dr. Anatoly Langer.
        /// </summary>
        public static string G35 {
            get {
                return ResourceManager.GetString("G35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string G36 {
            get {
                return ResourceManager.GetString("G36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Need for Lipid Lowering Beyond Statin Therapy.
        /// </summary>
        public static string G37 {
            get {
                return ResourceManager.GetString("G37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Behind PCSK9 Inhibitors.
        /// </summary>
        public static string G38 {
            get {
                return ResourceManager.GetString("G38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-world Data from the Goal Canada Program.
        /// </summary>
        public static string G39 {
            get {
                return ResourceManager.GetString("G39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sub-Investigator will receive an automatic email with the login instructions from.
        /// </summary>
        public static string G4 {
            get {
                return ResourceManager.GetString("G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal International Protocol.
        /// </summary>
        public static string G40 {
            get {
                return ResourceManager.GetString("G40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal International eCRF.
        /// </summary>
        public static string G41 {
            get {
                return ResourceManager.GetString("G41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentations.
        /// </summary>
        public static string G42 {
            get {
                return ResourceManager.GetString("G42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation 1.
        /// </summary>
        public static string G43 {
            get {
                return ResourceManager.GetString("G43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sub-Investigator will have access to the same site functionalities and resources as the Principal Investigator.
        /// </summary>
        public static string G5 {
            get {
                return ResourceManager.GetString("G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can modify/remove Sub-Investigators in the &quot;Modify Sub-I&quot; section of the left-hand menu.
        /// </summary>
        public static string G6 {
            get {
                return ResourceManager.GetString("G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string G7 {
            get {
                return ResourceManager.GetString("G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string G8 {
            get {
                return ResourceManager.GetString("G8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string G9 {
            get {
                return ResourceManager.GetString("G9", resourceCulture);
            }
        }
    }
}
